[workspace]
members = [
    "src/contract/simple_token",
    "src/contract/counter",
    "src/contract/depositum",
    "src/contract/ref_farming_strategy",
]

[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"
# Opt into extra safety checks on arithmetic operations https://stackoverflow.com/a/64136471/3123272
overflow-checks = true
