[advisories]
ignore = [
    "RUSTSEC-2020-0071",
    "RUSTSEC-2020-0159",
    "RUSTSEC-2021-0110",
    "RUSTSEC-2021-0089",
    "RUSTSEC-2020-0077",
]
# warn for categories of informational advisories
informational_warnings = [
    "unmaintained",
    "unsound",
]

[target]
arch = "wasm32"
