name: contract

on:
  push:
    paths:
      - '.cargo/**'
      - 'src/contract/**'
      - '!src/contract/**/*.ts'
      - '!src/contract/**/*.js'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'toolchain.toml'
    branches:
      - main
  pull_request:
    paths:
      - '.cargo/**'
      - 'src/contract/**'
      - '!src/contract/**/*.ts'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'toolchain.toml'
    branches:
      - main

jobs:

  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
          toolchain: stable
          components: rustfmt, clippy
          profile: minimal
          override: true
      - run: make qa

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
